### ISSUE TITLE
Add support for add device via IP

### ISSUE THREAD

**Issue by asteman** [henrikjonhed/se.hjonhed.robonect#1]
My robonect is on another subnet and cannot be found with mDNS. Support for adding device via IP would be nice.

**Comment by henrikjonhed** [comment]
Great suggestion @asteman! I've made an attempt in v1.0.13 to address this, feel free to try it out: https://homey.app/sv-se/app/se.hjonhed.robonect/Robonect/test/

**Comment by asteman** [comment]
Unfortunalty my mower decided to die and will be replaced. So I am unable to test at the moment. I'm sorry about that!

**Comment by henrikjonhed** [comment]
Sad to hear, hope that the replacement works better!
